# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-10.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/antRthorn/Dropbox/hpgem/Phoenix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/antRthorn/Dropbox/hpgem/Phoenix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-10.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-10.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	"/Applications/CMake 2.8-10.app/Contents/bin/ctest" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/antRthorn/Dropbox/hpgem/Phoenix/CMakeFiles /Users/antRthorn/Dropbox/hpgem/Phoenix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/antRthorn/Dropbox/hpgem/Phoenix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Matrix

# Build rule for target.
Matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Matrix
.PHONY : Matrix

# fast build rule for target.
Matrix/fast:
	$(MAKE) -f src/LinearAlgebra/CMakeFiles/Matrix.dir/build.make src/LinearAlgebra/CMakeFiles/Matrix.dir/build
.PHONY : Matrix/fast

#=============================================================================
# Target rules for targets named Geometry

# Build rule for target.
Geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Geometry
.PHONY : Geometry

# fast build rule for target.
Geometry/fast:
	$(MAKE) -f src/Geometry/CMakeFiles/Geometry.dir/build.make src/Geometry/CMakeFiles/Geometry.dir/build
.PHONY : Geometry/fast

#=============================================================================
# Target rules for targets named Reference_geometries

# Build rule for target.
Reference_geometries: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Reference_geometries
.PHONY : Reference_geometries

# fast build rule for target.
Reference_geometries/fast:
	$(MAKE) -f src/Geometry/CMakeFiles/Reference_geometries.dir/build.make src/Geometry/CMakeFiles/Reference_geometries.dir/build
.PHONY : Reference_geometries/fast

#=============================================================================
# Target rules for targets named QuadratureRules

# Build rule for target.
QuadratureRules: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QuadratureRules
.PHONY : QuadratureRules

# fast build rule for target.
QuadratureRules/fast:
	$(MAKE) -f src/Integration/QuadratureRules/CMakeFiles/QuadratureRules.dir/build.make src/Integration/QuadratureRules/CMakeFiles/QuadratureRules.dir/build
.PHONY : QuadratureRules/fast

#=============================================================================
# Target rules for targets named MatrixTest.out

# Build rule for target.
MatrixTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MatrixTest.out
.PHONY : MatrixTest.out

# fast build rule for target.
MatrixTest.out/fast:
	$(MAKE) -f tests/unit/LinearAlgebra/CMakeFiles/MatrixTest.out.dir/build.make tests/unit/LinearAlgebra/CMakeFiles/MatrixTest.out.dir/build
.PHONY : MatrixTest.out/fast

#=============================================================================
# Target rules for targets named VectorTest.out

# Build rule for target.
VectorTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VectorTest.out
.PHONY : VectorTest.out

# fast build rule for target.
VectorTest.out/fast:
	$(MAKE) -f tests/unit/LinearAlgebra/CMakeFiles/VectorTest.out.dir/build.make tests/unit/LinearAlgebra/CMakeFiles/VectorTest.out.dir/build
.PHONY : VectorTest.out/fast

#=============================================================================
# Target rules for targets named FaceGeometry.out

# Build rule for target.
FaceGeometry.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FaceGeometry.out
.PHONY : FaceGeometry.out

# fast build rule for target.
FaceGeometry.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/FaceGeometry.out.dir/build.make tests/unit/Geometry/CMakeFiles/FaceGeometry.out.dir/build
.PHONY : FaceGeometry.out/fast

#=============================================================================
# Target rules for targets named MappingHypercubeLinear_UnitTest.out

# Build rule for target.
MappingHypercubeLinear_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MappingHypercubeLinear_UnitTest.out
.PHONY : MappingHypercubeLinear_UnitTest.out

# fast build rule for target.
MappingHypercubeLinear_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/MappingHypercubeLinear_UnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/MappingHypercubeLinear_UnitTest.out.dir/build
.PHONY : MappingHypercubeLinear_UnitTest.out/fast

#=============================================================================
# Target rules for targets named MappingLineToSquare_UnitTest.out

# Build rule for target.
MappingLineToSquare_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MappingLineToSquare_UnitTest.out
.PHONY : MappingLineToSquare_UnitTest.out

# fast build rule for target.
MappingLineToSquare_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/MappingLineToSquare_UnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/MappingLineToSquare_UnitTest.out.dir/build
.PHONY : MappingLineToSquare_UnitTest.out/fast

#=============================================================================
# Target rules for targets named MappingPointToLine_UnitTest.out

# Build rule for target.
MappingPointToLine_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MappingPointToLine_UnitTest.out
.PHONY : MappingPointToLine_UnitTest.out

# fast build rule for target.
MappingPointToLine_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/MappingPointToLine_UnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/MappingPointToLine_UnitTest.out.dir/build
.PHONY : MappingPointToLine_UnitTest.out/fast

#=============================================================================
# Target rules for targets named MappingSimplexLinear_UnitTest.out

# Build rule for target.
MappingSimplexLinear_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MappingSimplexLinear_UnitTest.out
.PHONY : MappingSimplexLinear_UnitTest.out

# fast build rule for target.
MappingSimplexLinear_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/MappingSimplexLinear_UnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/MappingSimplexLinear_UnitTest.out.dir/build
.PHONY : MappingSimplexLinear_UnitTest.out/fast

#=============================================================================
# Target rules for targets named MappingSquareToCube_UnitTest.out

# Build rule for target.
MappingSquareToCube_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MappingSquareToCube_UnitTest.out
.PHONY : MappingSquareToCube_UnitTest.out

# fast build rule for target.
MappingSquareToCube_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/MappingSquareToCube_UnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/MappingSquareToCube_UnitTest.out.dir/build
.PHONY : MappingSquareToCube_UnitTest.out/fast

#=============================================================================
# Target rules for targets named PointPhysical_UnitTest.out

# Build rule for target.
PointPhysical_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PointPhysical_UnitTest.out
.PHONY : PointPhysical_UnitTest.out

# fast build rule for target.
PointPhysical_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/PointPhysical_UnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/PointPhysical_UnitTest.out.dir/build
.PHONY : PointPhysical_UnitTest.out/fast

#=============================================================================
# Target rules for targets named PointReference_UnitTest.out

# Build rule for target.
PointReference_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PointReference_UnitTest.out
.PHONY : PointReference_UnitTest.out

# fast build rule for target.
PointReference_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/PointReference_UnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/PointReference_UnitTest.out.dir/build
.PHONY : PointReference_UnitTest.out/fast

#=============================================================================
# Target rules for targets named Point_UnitTest.out

# Build rule for target.
Point_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Point_UnitTest.out
.PHONY : Point_UnitTest.out

# fast build rule for target.
Point_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/Point_UnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/Point_UnitTest.out.dir/build
.PHONY : Point_UnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferenceCubeUnitTest.out

# Build rule for target.
ReferenceCubeUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferenceCubeUnitTest.out
.PHONY : ReferenceCubeUnitTest.out

# fast build rule for target.
ReferenceCubeUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferenceCubeUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferenceCubeUnitTest.out.dir/build
.PHONY : ReferenceCubeUnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferenceHypercubeUnitTest.out

# Build rule for target.
ReferenceHypercubeUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferenceHypercubeUnitTest.out
.PHONY : ReferenceHypercubeUnitTest.out

# fast build rule for target.
ReferenceHypercubeUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferenceHypercubeUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferenceHypercubeUnitTest.out.dir/build
.PHONY : ReferenceHypercubeUnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferenceLineUnitTest.out

# Build rule for target.
ReferenceLineUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferenceLineUnitTest.out
.PHONY : ReferenceLineUnitTest.out

# fast build rule for target.
ReferenceLineUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferenceLineUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferenceLineUnitTest.out.dir/build
.PHONY : ReferenceLineUnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferencePointUnitTest.out

# Build rule for target.
ReferencePointUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferencePointUnitTest.out
.PHONY : ReferencePointUnitTest.out

# fast build rule for target.
ReferencePointUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferencePointUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferencePointUnitTest.out.dir/build
.PHONY : ReferencePointUnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferencePyramidUnitTest.out

# Build rule for target.
ReferencePyramidUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferencePyramidUnitTest.out
.PHONY : ReferencePyramidUnitTest.out

# fast build rule for target.
ReferencePyramidUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferencePyramidUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferencePyramidUnitTest.out.dir/build
.PHONY : ReferencePyramidUnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferenceSquareUnitTest.out

# Build rule for target.
ReferenceSquareUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferenceSquareUnitTest.out
.PHONY : ReferenceSquareUnitTest.out

# fast build rule for target.
ReferenceSquareUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferenceSquareUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferenceSquareUnitTest.out.dir/build
.PHONY : ReferenceSquareUnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferenceTetrahedronUnitTest.out

# Build rule for target.
ReferenceTetrahedronUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferenceTetrahedronUnitTest.out
.PHONY : ReferenceTetrahedronUnitTest.out

# fast build rule for target.
ReferenceTetrahedronUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferenceTetrahedronUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferenceTetrahedronUnitTest.out.dir/build
.PHONY : ReferenceTetrahedronUnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferenceTriangleUnitTest.out

# Build rule for target.
ReferenceTriangleUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferenceTriangleUnitTest.out
.PHONY : ReferenceTriangleUnitTest.out

# fast build rule for target.
ReferenceTriangleUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferenceTriangleUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferenceTriangleUnitTest.out.dir/build
.PHONY : ReferenceTriangleUnitTest.out/fast

#=============================================================================
# Target rules for targets named ReferenceTriangularPrismUnitTest.out

# Build rule for target.
ReferenceTriangularPrismUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReferenceTriangularPrismUnitTest.out
.PHONY : ReferenceTriangularPrismUnitTest.out

# fast build rule for target.
ReferenceTriangularPrismUnitTest.out/fast:
	$(MAKE) -f tests/unit/Geometry/CMakeFiles/ReferenceTriangularPrismUnitTest.out.dir/build.make tests/unit/Geometry/CMakeFiles/ReferenceTriangularPrismUnitTest.out.dir/build
.PHONY : ReferenceTriangularPrismUnitTest.out/fast

#=============================================================================
# Target rules for targets named BasisFunctionsTest.out

# Build rule for target.
BasisFunctionsTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasisFunctionsTest.out
.PHONY : BasisFunctionsTest.out

# fast build rule for target.
BasisFunctionsTest.out/fast:
	$(MAKE) -f tests/unit/Base/CMakeFiles/BasisFunctionsTest.out.dir/build.make tests/unit/Base/CMakeFiles/BasisFunctionsTest.out.dir/build
.PHONY : BasisFunctionsTest.out/fast

#=============================================================================
# Target rules for targets named CentaurMeshReaderTest.out

# Build rule for target.
CentaurMeshReaderTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CentaurMeshReaderTest.out
.PHONY : CentaurMeshReaderTest.out

# fast build rule for target.
CentaurMeshReaderTest.out/fast:
	$(MAKE) -f tests/unit/Base/CMakeFiles/CentaurMeshReaderTest.out.dir/build.make tests/unit/Base/CMakeFiles/CentaurMeshReaderTest.out.dir/build
.PHONY : CentaurMeshReaderTest.out/fast

#=============================================================================
# Target rules for targets named LevelTreeTest.out

# Build rule for target.
LevelTreeTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LevelTreeTest.out
.PHONY : LevelTreeTest.out

# fast build rule for target.
LevelTreeTest.out/fast:
	$(MAKE) -f tests/unit/Base/CMakeFiles/LevelTreeTest.out.dir/build.make tests/unit/Base/CMakeFiles/LevelTreeTest.out.dir/build
.PHONY : LevelTreeTest.out/fast

#=============================================================================
# Target rules for targets named RectangularMeshGeneratorTest.out

# Build rule for target.
RectangularMeshGeneratorTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RectangularMeshGeneratorTest.out
.PHONY : RectangularMeshGeneratorTest.out

# fast build rule for target.
RectangularMeshGeneratorTest.out/fast:
	$(MAKE) -f tests/unit/Base/CMakeFiles/RectangularMeshGeneratorTest.out.dir/build.make tests/unit/Base/CMakeFiles/RectangularMeshGeneratorTest.out.dir/build
.PHONY : RectangularMeshGeneratorTest.out/fast

#=============================================================================
# Target rules for targets named IntegrationUnitTest.out

# Build rule for target.
IntegrationUnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IntegrationUnitTest.out
.PHONY : IntegrationUnitTest.out

# fast build rule for target.
IntegrationUnitTest.out/fast:
	$(MAKE) -f tests/unit/Integration/CMakeFiles/IntegrationUnitTest.out.dir/build.make tests/unit/Integration/CMakeFiles/IntegrationUnitTest.out.dir/build
.PHONY : IntegrationUnitTest.out/fast

#=============================================================================
# Target rules for targets named IntegrationUnitTest2.out

# Build rule for target.
IntegrationUnitTest2.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IntegrationUnitTest2.out
.PHONY : IntegrationUnitTest2.out

# fast build rule for target.
IntegrationUnitTest2.out/fast:
	$(MAKE) -f tests/unit/Integration/CMakeFiles/IntegrationUnitTest2.out.dir/build.make tests/unit/Integration/CMakeFiles/IntegrationUnitTest2.out.dir/build
.PHONY : IntegrationUnitTest2.out/fast

#=============================================================================
# Target rules for targets named QuadratureRules_UnitTest.out

# Build rule for target.
QuadratureRules_UnitTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QuadratureRules_UnitTest.out
.PHONY : QuadratureRules_UnitTest.out

# fast build rule for target.
QuadratureRules_UnitTest.out/fast:
	$(MAKE) -f tests/unit/Integration/QuadratureRules/CMakeFiles/QuadratureRules_UnitTest.out.dir/build.make tests/unit/Integration/QuadratureRules/CMakeFiles/QuadratureRules_UnitTest.out.dir/build
.PHONY : QuadratureRules_UnitTest.out/fast

#=============================================================================
# Target rules for targets named TecplotOutputTest.out

# Build rule for target.
TecplotOutputTest.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TecplotOutputTest.out
.PHONY : TecplotOutputTest.out

# fast build rule for target.
TecplotOutputTest.out/fast:
	$(MAKE) -f tests/unit/Output/CMakeFiles/TecplotOutputTest.out.dir/build.make tests/unit/Output/CMakeFiles/TecplotOutputTest.out.dir/build
.PHONY : TecplotOutputTest.out/fast

#=============================================================================
# Target rules for targets named Problem.out

# Build rule for target.
Problem.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Problem.out
.PHONY : Problem.out

# fast build rule for target.
Problem.out/fast:
	$(MAKE) -f tests/problems/Basic/CMakeFiles/Problem.out.dir/build.make tests/problems/Basic/CMakeFiles/Problem.out.dir/build
.PHONY : Problem.out/fast

#=============================================================================
# Target rules for targets named app1.out

# Build rule for target.
app1.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app1.out
.PHONY : app1.out

# fast build rule for target.
app1.out/fast:
	$(MAKE) -f tests/problems/app1/CMakeFiles/app1.out.dir/build.make tests/problems/app1/CMakeFiles/app1.out.dir/build
.PHONY : app1.out/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Matrix"
	@echo "... Geometry"
	@echo "... Reference_geometries"
	@echo "... QuadratureRules"
	@echo "... MatrixTest.out"
	@echo "... VectorTest.out"
	@echo "... FaceGeometry.out"
	@echo "... MappingHypercubeLinear_UnitTest.out"
	@echo "... MappingLineToSquare_UnitTest.out"
	@echo "... MappingPointToLine_UnitTest.out"
	@echo "... MappingSimplexLinear_UnitTest.out"
	@echo "... MappingSquareToCube_UnitTest.out"
	@echo "... PointPhysical_UnitTest.out"
	@echo "... PointReference_UnitTest.out"
	@echo "... Point_UnitTest.out"
	@echo "... ReferenceCubeUnitTest.out"
	@echo "... ReferenceHypercubeUnitTest.out"
	@echo "... ReferenceLineUnitTest.out"
	@echo "... ReferencePointUnitTest.out"
	@echo "... ReferencePyramidUnitTest.out"
	@echo "... ReferenceSquareUnitTest.out"
	@echo "... ReferenceTetrahedronUnitTest.out"
	@echo "... ReferenceTriangleUnitTest.out"
	@echo "... ReferenceTriangularPrismUnitTest.out"
	@echo "... BasisFunctionsTest.out"
	@echo "... CentaurMeshReaderTest.out"
	@echo "... LevelTreeTest.out"
	@echo "... RectangularMeshGeneratorTest.out"
	@echo "... IntegrationUnitTest.out"
	@echo "... IntegrationUnitTest2.out"
	@echo "... QuadratureRules_UnitTest.out"
	@echo "... TecplotOutputTest.out"
	@echo "... Problem.out"
	@echo "... app1.out"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

