//
// Created by root on 2/5/16.
//

#ifndef HPGEM_SERIALIZATIONCOMMANDS_H
#define HPGEM_SERIALIZATIONCOMMANDS_H

BOOST_SERIALIZATION_ASSUME_ABSTRACT(Base::CoordinateTransformation<DIM>);

#endif //HPGEM_SERIALIZATIONCOMMANDS_H
