#!/bin/bash

#This does the testing of newly created data against pre computed gold data
#It is just a simple bash script
#It is called by cmake and the arguments are $1='gold data file name', $2='local created file name' 


#testlogname is the log file that will store temporary data and error message it any
testlogname=$2.errorlog

#remove the old errorlog from the last run. If it exists, -f is used to surpress the does not exit 
rm -f $testlogname

#Write the date the test was run to the testlogfile
date=$(date)
echo Test run on $date >> $testlogname

#run the fpdiff command and write the out to testlogfile
${0/self_test/fpdiff.py} $1 $2 >> $testlogname || echo "FAILED to execute: ${0/self_test/fpdiff.py} $1 $2" >> $testlogname

#If the work FAILED is in the testlogfile it failed.
failed=$(less $testlogname | grep FAILED --count)
echo $failed >> $testlogname

if [ $failed == 0 ]; then
	#If it did not failed removed the testlogfile and return 0

	rm $testlogname
	exit 0
else
	#if failed leave testlogfile file and return 1
    cat $testlogname
	exit 1
fi

# Code should never get here but if you did something when wrong return 1
exit 1
