/*
 This file forms part of hpGEM. This package has been developed over a number of years by various people at the University of Twente and a full list of contributors can be found at
 http://hpgem.org/about-the-code/team
 
 This code is distributed using BSD 3-Clause License. A copy of which can found below.
 
 
 Copyright (c) 2014, University of Twente
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 
 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 
 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 
 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//This test validates that, for meshes generated by the rectangular mesh generator:
//-all IDs assigned to elements, faces or edges are unique (but there may be an edge, a face and an element that share the same ID)
//-all elements connected to a face or an edge agree on the location of this face/edge and on the identity of the face/edge
//-all faces and all edges of an element are defined
//added all of the above for vertices
//periodic meshes need a different test
#include "Base/MeshManipulator.h"
#include "Base/Edge.h"
#include "Base/Element.h"
#include "Base/Face.h"
#include "Base/RectangularMeshDescriptor.h"
#include "Geometry/ReferenceGeometry.h"
#include "Geometry/PhysicalGeometry.h"
#include "Geometry/PointReference.h"
#include "Base/ElementCacheData.h"
#include "Base/FaceCacheData.h"
#include "Base/ConfigurationData.h"
#include "Base/CommandLineOptions.h"
#include "Logger.h"

#include <unordered_set>

template<std::size_t DIM>
void testMesh(Base::MeshManipulator<DIM>* test)
{
    std::unordered_set<std::size_t> elementIDs, faceIDs, edgeIDs, nodeIDs;
    for (Base::Element* element : test->getElementsList())
    {
        logger.assert_always(elementIDs.find(element->getID()) == elementIDs.end(), "duplicate element ID (%)", element->getID());
        elementIDs.insert(element->getID());
        logger.assert_always(element->getNumberOfFaces() == element->getReferenceGeometry()->getNrOfCodim1Entities(), "confusion about the number of faces");
        if (test->dimension() == 2)
        {
            logger.assert_always(element->getNumberOfEdges() == 0, "confusion about the number of edges");
        }
        else
        {
            logger.assert_always(element->getNumberOfEdges() == element->getReferenceGeometry()->getNrOfCodim2Entities(), "confusion about the number of edges");
        }
        logger.assert_always(element->getNumberOfNodes() == element->getReferenceGeometry()->getNumberOfNodes(), "confusion about the number of vertices");
        for (std::size_t i = 0; i < element->getNumberOfFaces(); ++i)
        {
            logger.assert_always(element->getFace(i) != nullptr, "missing Face");
        }
        for (std::size_t i = 0; i < element->getNumberOfEdges(); ++i)
        {
            logger.assert_always(element->getEdge(i) != nullptr, "missing Face");
        }
        for (std::size_t i = 0; i < element->getNumberOfNodes(); ++i)
        {
            logger.assert_always(element->getNode(i) != nullptr, "missing Face");
        }
    }
    for (Base::Face* face : test->getFacesList())
    {
        logger.assert_always(faceIDs.find(face->getID()) == faceIDs.end(), "duplicate face ID");
        faceIDs.insert(face->getID());
        logger.assert_always(face->getPtrElementLeft()->getFace(face->localFaceNumberLeft()) == face, "element<->face matching");
        if (face->isInternal())
        {
            std::vector<std::size_t> leftNodes(face->getReferenceGeometry()->getNumberOfNodes()), rightNodes(leftNodes);
            leftNodes = face->getPtrElementLeft()->getPhysicalGeometry()->getGlobalFaceNodeIndices(face->localFaceNumberLeft());
            rightNodes = face->getPtrElementRight()->getPhysicalGeometry()->getGlobalFaceNodeIndices(face->localFaceNumberRight());
            for (std::size_t i = 0; i < leftNodes.size(); ++i)
            {
                bool found = false;
                for (std::size_t j = 0; j < rightNodes.size(); ++j)
                {
                    found |= leftNodes[i] == rightNodes[j];
                }
                logger.assert_always(found, "face positioning");
            }
            logger.assert_always(leftNodes.size() == rightNodes.size(), "face positioning");
            logger.assert_always(face->getPtrElementRight()->getFace(face->localFaceNumberRight()) == face, "element<->face matching");
        }
    }
    for (Base::Edge* edge : test->getEdgesList())
    {
        logger.assert_always(edgeIDs.find(edge->getID()) == edgeIDs.end(), "duplicate edge ID");
        edgeIDs.insert(edge->getID());
        logger.assert_always(edge->getElement(0)->getEdge(edge->getEdgeNr(0)) == edge, "element<->edge matching");
        std::vector<std::size_t> firstNodes(edge->getElement(0)->getReferenceGeometry()->getCodim2ReferenceGeometry(edge->getEdgeNr(0))->getNumberOfNodes()), otherNodes(firstNodes);
        firstNodes = edge->getElement(0)->getReferenceGeometry()->getCodim2EntityLocalIndices(edge->getEdgeNr(0));
        for (std::size_t i = 0; i < firstNodes.size(); ++i)
        {
            firstNodes[i] = edge->getElement(0)->getPhysicalGeometry()->getNodeIndex(firstNodes[i]);
        }
        for (std::size_t i = 1; i < edge->getNrOfElements(); ++i)
        {
            logger.assert_always(edge->getElement(i)->getEdge(edge->getEdgeNr(i)) == edge, "element<->edge matching");
            otherNodes = edge->getElement(i)->getReferenceGeometry()->getCodim2EntityLocalIndices(edge->getEdgeNr(i));
            for (std::size_t j = 0; j < otherNodes.size(); ++j)
            {
                otherNodes[j] = edge->getElement(i)->getPhysicalGeometry()->getNodeIndex(otherNodes[j]);
            }
            for (std::size_t k = 0; k < firstNodes.size(); ++k)
            {
                bool found = false;
                for (std::size_t j = 0; j < otherNodes.size(); ++j)
                {
                    found |= firstNodes[k] == otherNodes[j];
                }
                logger.assert_always(found, "edge positioning");
            }
            logger.assert_always(firstNodes.size() == otherNodes.size(), "edge positioning");
        }
    }
    for (Base::Node* node : test->getNodesList())
    {
        logger.assert_always(nodeIDs.find(node->getID()) == nodeIDs.end(), "duplicate node ID");
        nodeIDs.insert(node->getID());
        logger.assert_always(node->getElement(0)->getNode(node->getNodeNr(0)) == node, "element<->node matching");
        Geometry::PointPhysical<DIM> pFirst, pOther;
        pFirst = node->getElement(0)->getPhysicalGeometry()->getLocalNodeCoordinates(node->getNodeNr(0));
        for (std::size_t i = 1; i < node->getNrOfElements(); ++i)
        {
            logger.assert_always(node->getElement(i)->getNode(node->getNodeNr(i)) == node, "element<->node matching");
            pOther = node->getElement(i)->getPhysicalGeometry()->getLocalNodeCoordinates(node->getNodeNr(i));
            logger.assert_always(pFirst == pOther, "node positioning");
        }
    }
    logger.assert_always(test->getNumberOfNodes() == test->getNumberOfNodeCoordinates(), "total amount of nodes != amount of grid points");
}

template<std::size_t DIM>
void testPointPhysicalsOfElementsOfCopiedMesh(Base::MeshManipulator<DIM>* mesh, Base::MeshManipulator<DIM>* meshCopy)
{
    std::vector<Base::Element*> eltsMesh = mesh->getElementsList();
    std::vector<Base::Element*> eltsMeshCopy = meshCopy->getElementsList();
    logger.assert_always(eltsMesh.size() == eltsMeshCopy.size(), "The copy does not have the same number of elements as the original MeshManipulator.");
    for (std::size_t i = 0; i < eltsMesh.size(); ++i)
    {
        logger.assert_always(eltsMesh[i]->getNumberOfNodes() == eltsMeshCopy[i]->getNumberOfNodes(), "The points of Element % are different.", i);
        for(std::size_t j = 0; j < eltsMesh[i]->getNumberOfNodes(); ++j)
        {
            const Geometry::PointPhysical<DIM>& first = eltsMesh[i]->getPhysicalGeometry()->getLocalNodeCoordinates(j);
            logger.assert_always(first == eltsMeshCopy[i]->getPhysicalGeometry()->getLocalNodeCoordinates(j), "The point % of Element % is different.", j, i);
        }
    }
}

int main(int argc, char** argv)
{
    Base::parse_options(argc, argv);
    // dim 1
    Base::RectangularMeshDescriptor<1> description1D;
    Base::RectangularMeshDescriptor<2> description2D;
    Base::RectangularMeshDescriptor<3> description3D;
    description1D.bottomLeft_[0] = 0;
    description2D.bottomLeft_[0] = 0;
    description2D.bottomLeft_[1] = 0;
    description3D.bottomLeft_[0] = 0;
    description3D.bottomLeft_[1] = 0;
    description3D.bottomLeft_[2] = 0;
    description1D.topRight_[0] = 1;
    description2D.topRight_[0] = 1;
    description2D.topRight_[1] = 1;
    description3D.topRight_[0] = 1;
    description3D.topRight_[1] = 1;
    description3D.topRight_[2] = 1;
    description1D.boundaryConditions_[0] = Base::BoundaryType::SOLID_WALL;
    description2D.boundaryConditions_[0] = Base::BoundaryType::SOLID_WALL;
    description2D.boundaryConditions_[1] = Base::BoundaryType::SOLID_WALL;
    description3D.boundaryConditions_[0] = Base::BoundaryType::SOLID_WALL;
    description3D.boundaryConditions_[1] = Base::BoundaryType::SOLID_WALL;
    description3D.boundaryConditions_[2] = Base::BoundaryType::SOLID_WALL;
    
    description1D.numElementsInDIM_[0] = 2;
    
    Base::MeshManipulator<1> *test = new Base::MeshManipulator<1>(new Base::ConfigurationData(1, 1, 2, 0), Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, 2, 0);
    test->createTriangularMesh(description1D.bottomLeft_, description1D.topRight_, description1D.numElementsInDIM_);
    
    testMesh(test);
    logger.assert_always(test->getNumberOfElements() == 2, "number of elements");
    
    delete test;
    description1D.numElementsInDIM_[0] = 3;
    
    test = new Base::MeshManipulator<1>(new Base::ConfigurationData(1, 1, 2, 0), Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, 2, 0);
    test->createTriangularMesh(description1D.bottomLeft_, description1D.topRight_, description1D.numElementsInDIM_);
    
    testMesh(test);
    logger.assert_always(test->getNumberOfElements() == 3, "number of elements");
    
    // dim 2
    
    delete test;
    description2D.numElementsInDIM_[0] = 2;
    description2D.numElementsInDIM_[1] = 3;
    
    Base::MeshManipulator<2> *test2 = new Base::MeshManipulator<2>(new Base::ConfigurationData(2, 1, 2, 0), Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, 2, 0);
    test2->createTriangularMesh(description2D.bottomLeft_, description2D.topRight_, description2D.numElementsInDIM_);
    
    testMesh(test2);
    logger.assert_always(test2->getNumberOfElements() == 12, "number of elements");
    
    delete test2;
    description2D.numElementsInDIM_[0] = 3;
    description2D.numElementsInDIM_[1] = 2;
    
    test2 = new Base::MeshManipulator<2>(new Base::ConfigurationData(2, 1, 2, 0), Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, 2, 0);
    test2->createTriangularMesh(description2D.bottomLeft_, description2D.topRight_, description2D.numElementsInDIM_);
    
    testMesh(test2);
    logger.assert_always(test2->getNumberOfElements() == 12, "number of elements");
    
    // dim 3
    
    delete test2;
    description3D.numElementsInDIM_[0] = 2;
    description3D.numElementsInDIM_[1] = 2;
    description3D.numElementsInDIM_[2] = 3;
    
    Base::MeshManipulator<3> *test3 = new Base::MeshManipulator<3>(new Base::ConfigurationData(3, 1, 2, 0), Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, 2, 0);
    test3->createTriangularMesh(description3D.bottomLeft_, description3D.topRight_, description3D.numElementsInDIM_);
    
    testMesh(test3);
    logger.assert_always(test3->getNumberOfElements() == 60, "number of elements");
    
    delete test3;
    description3D.numElementsInDIM_[0] = 2;
    description3D.numElementsInDIM_[1] = 3;
    description3D.numElementsInDIM_[2] = 2;
    
    test3 = new Base::MeshManipulator<3>(new Base::ConfigurationData(3, 1, 2, 0), Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, 2, 0);
    test3->createTriangularMesh(description3D.bottomLeft_, description3D.topRight_, description3D.numElementsInDIM_);
    
    testMesh(test3);
    logger.assert_always(test3->getNumberOfElements() == 60, "number of elements");
    
    delete test3;
    description3D.numElementsInDIM_[0] = 3;
    description3D.numElementsInDIM_[1] = 2;
    description3D.numElementsInDIM_[2] = 2;
    
    test3 = new Base::MeshManipulator<3>(new Base::ConfigurationData(3, 1, 2, 0), Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, Base::BoundaryType::SOLID_WALL, 2, 0);
    test3->createTriangularMesh(description3D.bottomLeft_, description3D.topRight_, description3D.numElementsInDIM_);
    
    testMesh(test3);
    logger.assert_always(test3->getNumberOfElements() == 60, "number of elements");
    
    //test copy constructor of MeshManipulator, only for most difficult case
    Base::MeshManipulator<3>* test4 = new Base::MeshManipulator<3>(*test3);
    testMesh(test4);
    logger.assert_always(test4->getNumberOfElements() == 60, "number of elements in copy");
    testPointPhysicalsOfElementsOfCopiedMesh(test3, test4);
    
    delete test3;
    delete test4;

    return 0;
}

