name: Basic CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Workflow name included as the job-id is sometimes listed without workflow name.
  run-tests-basic:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ ON, OFF ] 
        compiler: [g++, clang++]
        BUILD_TYPE : [Debug, Release]
    steps:
    - uses: actions/checkout@v2 
    - name: dependencies
      run: |
        sudo apt update
        sudo apt install libblas-dev liblapack-dev libopenmpi-dev libmetis-dev petsc-dev slepc-dev
    - name: configure
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake -H. -Bbuild -DhpGEM_USE_MPI=${{ matrix.mpi }} -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DhpGEM_USE_METIS=ON -DhpGEM_USE_PETSC=${{ matrix.mpi }} -DhpGEM_USE_SLEPC=${{ matrix.mpi }} 
    - name: make
      run: cmake --build build -- -j4
    - name: test
      run: cd build && ctest --output-on-failure
