name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: dependencies
      run: sudo apt install libblas-dev liblapack-dev 
    - name: configure
      run: cmake -H. -Bbuild 
    - name: make
      run: cmake --build build -- -j4
    - name: test
      run: cd build && ctest
