name: Basic CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ ON, OFF ] 
    steps:
    - uses: actions/checkout@v2 
    - name: blaslapack
      run: sudo apt install libblas-dev liblapack-dev libopenmpi-dev
    - name: configure
      run: cmake -H. -Bbuild -DhpGEM_USE_MPI=${{ matrix.mpi }} -DENABLE_TESTING=ON
    - name: make
      run: cmake --build build -- -j4
    - name: test
      run: cd build && ctest
