name: Codecov
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-coverage:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ ON] 
        compiler: [gcc]
        BUILD_TYPE : [Debug]
    steps:
    - uses: actions/checkout@v2 
    - name: blaslapack
      run: |
        sudo apt update
        sudo apt install libblas-dev liblapack-dev libopenmpi-dev libmetis-dev libpetsc-complex-dev libslepc-complex-dev
    - name: configure
      env:
        CC: ${{ matrix.compiler }}
      run: cmake -H. -Bbuild -DhpGEM_USE_MPI=${{ matrix.mpi }} -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DhpGEM_USE_METIS=ON -DhpGEM_USE_COMPLEX_PETSC=${{ matrix.mpi }} -DhpGEM_USE_SLEPC=${{ matrix.mpi }} -DCMAKE_CXX_FLAGS="-O2" -DENABLE_COVERAGE_BUILD=ON
    - name: make
      run: cmake --build build -- -j4
    - name: test
      run: cd build && ctest --output-on-failure
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
