name: PETSC_complex

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Workflow name included as the job-id is sometimes listed without workflow name.
  run-tests-complex-petsc:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ ON ] 
        compiler: [gcc]
        BUILD_TYPE : [Debug, Release]
    steps:
    - uses: actions/checkout@v2 
    - name: dependencies
      run: sudo apt install libblas-dev liblapack-dev libopenmpi-dev libpetsc-complex-3.7-dev libslepc-complex-3.7-dev
    - name: configure
      env:
        CC: ${{ matrix.compiler }}
      run: cmake -H. -Bbuild -DhpGEM_USE_MPI=${{ matrix.mpi }} -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DhpGEM_USE_COMPLEX_PETSC=${{ matrix.mpi }} -DhpGEM_USE_SLEPC=${{ matrix.mpi }} 
    - name: make
      run: cmake --build build -- -j4
    - name: test
      run: cd build && ctest -V -R DGmax_Vacuum2D_SelfTest && ctest
