name: Qhull

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ ON, OFF ] 
        compiler: [gcc]
        BUILD_TYPE : [Debug, Release]
    steps:
    - uses: actions/checkout@v2 
    - name: dependencies
      run: sudo apt install libblas-dev liblapack-dev libqhull-dev libslepc-complex-3.7-dev
    - name: configure
      env:
        CC: ${{ matrix.compiler }}
      run: cmake -H. -Bbuild -DhpGEM_USE_MPI=${{ matrix.mpi }} -DENABLE_TESTING=ON -DCMAKEBUILD_TYPE=${{ matrix.BUILD_TYPE }} -DhpGEM_USE_QHULL=ON
    - name: make
      run: cmake --build build -- -j4
    - name: test
      run: cd build && ctest
